openapi: 3.0.3
info:
  title: terra-cloud-transparency-manager
  description: terra-cloud-transparency-manager
  version: 0.0.1
paths:
  /status:
    get:
      summary: Check status of the service
      tags: [ public ]
      operationId: getStatus
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/SystemStatusResponse'

  /version:
    get:
      summary: Get version info of the deployed service
      tags: [ public ]
      operationId: getVersion
      security: [ ]
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionProperties'
        '404':
          description: "Version not configured"
        '500':
          $ref: '#/components/responses/ServerError'

  # README /docs/api_versioning.md
  /api/cloudTransparentAccess/v1:
    get:
      summary: Gets cloud transparent accesses for the calling user
      tags: [ cloudTransparentAccess ]
      operationId: getCloudTransparentAccesses
      responses:
        '200':
          description: The resources the user has cloud transparent access to
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloudTransparentAccess'
        '404':
          description: User not found
        '500':
          $ref: '#/components/responses/ServerError'
  /api/cloudTransparentAccess/v1/{resourceType}/{resourceId}:
    put:
      summary: Enables cloud transparent access for the calling user on the specified resource
      tags: [ cloudTransparentAccess ]
      operationId: putCloudTransparentAccess
      parameters:
        - name: resourceType
          in: path
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cloud transparent access enabled
        '404':
          description: Resource not found
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      summary: Disables cloud transparent access for the calling user on the specified resource
      tags: [ cloudTransparentAccess ]
      operationId: deleteCloudTransparentAccess
      parameters:
        - name: resourceType
          in: path
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cloud transparent access disabled
        '404':
          description: Resource not found
        '500':
          $ref: '#/components/responses/ServerError'

components:
  responses:
    SystemStatusResponse:
      description: A JSON description of the subsystems and their statuses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

    # Error Responses
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    PermissionDenied:
      description: Permission denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:
    CloudTransparentAccess:
      type: object
      properties:
        samUserId:
          type: string
        resourceType:
          type: string
        resourceId:
          type: string
        enabled:
          type: boolean
    ErrorReport:
      type: object
      required: [ message, statusCode ]
      properties:
        message:
          type: string
        statusCode:
          type: integer

    SystemStatus:
      required: [ ok, systems ]
      type: object
      properties:
        ok:
          type: boolean
          description: whether any system(s) need attention
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    VersionProperties:
      type: object
      properties:
        gitTag:
          type: string
        gitHash:
          type: string
        github:
          type: string
        build:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: [ ]
